CREATE TABLE CIENTIFICOS (
DNI INTEGER,
NOMAPELS CHARACTER(40),
PRIMARY KEY(DNI))

CREATE TABLE PROYECTO (
ID_PROYECTO INTEGER,
NOMBRE CHARACTER(30),
HORAS INTEGER,
PRIMARY KEY(ID_PROYECTO))

CREATE TABLE ASIGNADO_A(
CIENTIFICO INTEGER,
PROYECTO INTEGER,
PRIMARY KEY(CIENTIFICO, PROYECTO),
FOREIGN KEY(CIENTIFICO) REFERENCES CIENTIFICOS(DNI),
FOREIGN KEY (PROYECTO) REFERENCES PROYECTO(ID_PROYECTO))

INSERT INTO CIENTIFICOS VALUES(1,'JOSE PEREZ');
INSERT INTO CIENTIFICOS VALUES(2,'CARLOS CASTRO');
INSERT INTO CIENTIFICOS VALUES(3,'ANA MARTINEZ');
INSERT INTO CIENTIFICOS VALUES(4,'MARIA ZAPATA');
SELECT * FROM CIENTIFICOS

INSERT INTO PROYECTO VALUES(1,'PROYECTO GAMA',25);
INSERT INTO PROYECTO VALUES(2,'PROYECTO SOLES',56);
INSERT INTO PROYECTO VALUES(3,'PROYECTO AZUL',20);
INSERT INTO PROYECTO VALUES(4,'PROYECTO ORO',40);
SELECT * FROM PROYECTO

INSERT INTO ASIGNADO_A VALUES(1,2);
INSERT INTO ASIGNADO_A VALUES(3,1);
INSERT INTO ASIGNADO_A VALUES(2,3);
INSERT INTO ASIGNADO_A VALUES(2,1);
SELECT * FROM ASIGNADO_A


--------------------- SOLUCION -----------------------
--PUNTO 1
SELECT DNI, NOMAPELS, ID_PROYECTO, NOMBRE
FROM CIENTIFICOS CI, ASIGNADO_A AA, PROYECTO PR
WHERE CI.DNI=AA.CIENTIFICO AND PR.ID_PROYECTO=AA.PROYECTO
ORDER BY NOMAPELS

SELECT DNI, NOMAPELS, ID_PROYECTO, NOMBRE
FROM CIENTIFICOS CI JOIN ASIGNADO_A AA ON CI.DNI=AA.CIENTIFICO
JOIN PROYECTO PR ON PR.ID_PROYECTO=AA.PROYECTO
ORDER BY NOMAPELS

--EN LA SIGUIENTE SOLUCION SE INCLUYEN LOS CIENTIFICOS QUE NO TIENEN
--PROYECTOS ASIGNADOS Y LOS PROYECTOS QUE NO SE LE HAN ASIGNADO
--CIENTIFICOS
SELECT DNI, NOMAPELS, ID_PROYECTO, NOMBRE
FROM CIENTIFICOS CI FULL JOIN ASIGNADO_A AA ON CI.DNI=AA.CIENTIFICO
FULL JOIN PROYECTO PR ON PR.ID_PROYECTO=AA.PROYECTO
ORDER BY NOMAPELS

--PUNTO 2
SELECT DNI, NOMAPELS, COUNT(CIENTIFICO) CANTIDAD_PROYECTOS
FROM CIENTIFICOS, ASIGNADO_A
WHERE DNI=CIENTIFICO
GROUP BY DNI, NOMAPELS
ORDER BY NOMAPELS

SELECT DNI, NOMAPELS, COUNT(CIENTIFICO) CANTIDAD_PROYECTOS
FROM CIENTIFICOS JOIN ASIGNADO_A
ON DNI=CIENTIFICO
GROUP BY DNI, NOMAPELS
ORDER BY NOMAPELS

--EN LA SIGUIENTE SOLUCION SE INCLUYE A LOS CINETIFCOS QUE NO
--TIENEN PROYECTOS ASIGNADO
SELECT DNI, NOMAPELS, COUNT(CIENTIFICO) CANTIDAD_PROYECTOS
FROM CIENTIFICOS LEFT JOIN ASIGNADO_A
ON DNI=CIENTIFICO
GROUP BY DNI, NOMAPELS
ORDER BY NOMAPELS

--PUNTO 3
SELECT ID_PROYECTO, NOMBRE, COUNT(PROYECTO) CANTIDAD_CIENTIFICOS
FROM PROYECTO, ASIGNADO_A
WHERE ID_PROYECTO=PROYECTO
GROUP BY ID_PROYECTO, NOMBRE
ORDER BY NOMBRE

SELECT ID_PROYECTO, NOMBRE, COUNT(PROYECTO) CANTIDAD_CIENTIFICOS
FROM PROYECTO JOIN ASIGNADO_A
ON ID_PROYECTO=PROYECTO
GROUP BY ID_PROYECTO, NOMBRE
ORDER BY NOMBRE

--ESTA SOLUCION INCLUYE LOS PROYECTOS QUE NO TIENEN CIENTIFICOS ASIGNADOS 
SELECT ID_PROYECTO, NOMBRE, COUNT(PROYECTO) CANTIDAD_CIENTIFICOS
FROM PROYECTO LEFT JOIN ASIGNADO_A
ON ID_PROYECTO=PROYECTO
GROUP BY ID_PROYECTO, NOMBRE
ORDER BY NOMBRE

--PUNTO 4
SELECT DNI, NOMAPELS, SUM(HORAS) DEDICACION
FROM CIENTIFICOS, ASIGNADO_A, PROYECTO
WHERE DNI=CIENTIFICO AND ID_PROYECTO=PROYECTO
GROUP BY DNI, NOMAPELS
ORDER BY DEDICACION DESC

SELECT DNI, NOMAPELS, SUM(HORAS) DEDICACION
FROM CIENTIFICOS JOIN ASIGNADO_A ON DNI=CIENTIFICO JOIN PROYECTO ON ID_PROYECTO=PROYECTO
GROUP BY DNI, NOMAPELS
ORDER BY DEDICACION DESC

--PUNTO 5
SELECT DNI, NOMAPELS FROM CIENTIFICOS
WHERE (SELECT COUNT(*) FROM ASIGNADO_A WHERE CIENTIFICO=DNI)>1 AND
(SELECT AVG(HORAS) FROM PROYECTO, ASIGNADO_A WHERE PROYECTO=ID_PROYECTO AND 
 CIENTIFICO=DNI)>22

--MOSTRAR LOS CIENTIFCOS QUE TENGAN UNA DEDICACIÓN PROMEDIO SUPERIOR A 23 HORAS
SELECT DNI, NOMAPELS, AVG(HORAS) DEDICACION
FROM CIENTIFICOS JOIN ASIGNADO_A ON DNI=CIENTIFICO JOIN PROYECTO ON ID_PROYECTO=PROYECTO
GROUP BY DNI, NOMAPELS
HAVING AVG(HORAS)>23
ORDER BY DEDICACION DESC
